#!/bin/bash
build() {
    add_binary /usr/lib/systemd/systemd-volatile-root

    add_systemd_unit systemd-volatile-root.service
}

help() {
    cat <<HELPEOF
Add systemd for volatile root
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
