#!/bin/bash -ex
PACKAGE_DIR=/build/desktop/packages \
SYNC_FILES="etc/fonts/ etc/pulse/ etc/NetworkManager/" \
PROFILE_FILES="/build/desktop/files" \
HOOKS="sd-plymouth keyboard sd-vconsole sd-encrypt" \
MODULES="i915" \
SYSTEMD_SERVICES="pcscd.service bluetooth.service gdm.service cloud-init-local.service cloud-final.service" \
SYSTEMD_USER_SERVICES="docker.service" \
post-install

if [ -f "/etc/libccid_Info.plist" ]
then
  rm /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist && cp /etc/libccid_Info.plist /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
fi

# disable ssh for cloud init

sed -i 's/^.*sshd.*$//' /usr/lib/systemd/system/cloud-init.service
sed -i 's/^.*systemd-networkd.*$//' /usr/lib/systemd/system/cloud-init.service
rm /usr/lib/systemd/system/systemd-network*
rm /usr/lib/systemd/system/docker*
plymouth-set-default-theme -R dark-arch

for i in /etc/mkinitcpio.d/*
do
  mkinitcpio -p $(basename $i .preset)
done
