#!/bin/bash -ex
PACKAGE_DIR=/build/desktop/packages \
SYNC_FILES="etc/fonts/ etc/pulse/ etc/NetworkManager/" \
PROFILE_FILES="/build/desktop/files" \
HOOKS="sd-plymouth keyboard sd-vconsole sd-encrypt" \
MODULES="i915" \
SYSTEMD_SERVICES="pcscd.service bluetooth.service gdm.service" \
SYSTEMD_USER_SERVICES="docker.service" \
post-install

if [ -f "/etc/dbus-1/system.d/wpa_supplicant.conf" ]
then
  mv -v /etc/dbus-1/system.d/wpa_supplicant.conf /usr/share/dbus-1/system.d/wpa_supplicant.conf
fi

if [ -f "/etc/libccid_Info.plist" ]
then
  rm /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist && cp /etc/libccid_Info.plist /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
fi

rm /usr/lib/systemd/system/sshdgenkeys.service
rm /usr/lib/systemd/system/docker*

find /usr/lib/systemd/
plymouth-set-default-theme -R dark-arch

for i in /etc/mkinitcpio.d/*
do
  mkinitcpio -p $(basename $i .preset)
done
