#!/bin/bash
build() {
    add_binary /usr/bin/rsync
    add_binary /usr/bin/setup-customize

    add_systemd_unit setup-customize-initrd.service
    add_systemd_unit setup-profile-home.service
}

help() {
    cat <<HELPEOF
Add systemd for localization
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
